language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - export LOGS_DB_URI='postgresql://postgres:@localhost:5432/travis_ci_test'
